services:
  frontend:
    image: nginx
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/usr/share/nginx/html:ro

  
  server:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: coffee_follower
    environment:
      - DATABASE_CONNECTION_STRING=postgresql://user:MyStrongPassword@database:5432/coffee
    depends_on:
      - database
    develop:
      watch:
        - path: ./src
          action: rebuild
    volumes:
      - ./logs:/app/logs
  database:
    image: postgres:16-alpine3.20
    container_name: database
    environment:
      - POSTGRES_PASSWORD=MyStrongPassword
      - POSTGRES_USER=user
      - POSTGRES_DB=coffee
