server:
  http_listen_port: 9080
  profiling_enabled: true

positions:
  filename: /var/positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "app logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "coffee-app"
          __path__: "/var/log/app.log"
    pipeline_stages:
      - json:
          expressions:
            level: levelname
            message: message
            timestamp: asctime
      - labels:
          level: level 
          message: message
      - timestamp:
          format: RFC3339N
          source: timestamp
      - output:
          source: message

  - job_name: "coffee logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "coffee-app"
          __path__: "/var/log/coffee.log"
    pipeline_stages:
      - json:
          expressions:
            level: levelname
            message: message
            timestamp: asctime
      - labels:
          level: level 
          message: message
          time: timestamp
      - timestamp:
          format: RFC3339
          source: timestamp
      - output:
          source: message